spring:
  datasource:
    hikari1:
      username: multitxtest
      password: multitxtest
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://133.186.145.158:11306/multi_tx_test
    hikari2:
      url:
      username: multitxtest
      password: multitxtest
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://133.186.145.141:11306/multi_tx_test